# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Minhyeok Lee
title: Integrated M.S/Ph.D Student
email: hydragon516@yonsei.ac.kr
# email_title: Email (Email title override)
phone: +82-10-4621-4054
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  Hydragon516
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
googlescholar_username: WGchT7cAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I am an integrated M.S/Ph.D student of computer vision at Yonsei University. I am interested in exploring <mark>Computer Vision</mark>, <mark>Semantic Segmentation</mark> and <mark>Autonomous Vehicle</mark>.
  
  To know more about me, please check out my CV or visit my <a href="https://github.com/Hydragon516">Github</a>.
# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Publication
    layout: text
    content: |
      * **SPSN: Superpixel Prototype Sampling Network for RGB-D Salient Object Detection (ECCV 2022)** <a href="https://github.com/Hydragon516/SPSN">[Code]</a>
        - __Minhyeok Lee\*__, Chaewon Park\*, Suhwan Cho, Sangyoun Lee
      * **Tackling Background Distraction in Video Object Segmentation (ECCV 2020)** <a href="https://github.com/suhwan-cho/TBD">[Code]</a>
        - Suhwan Cho, Heansung Lee, **Minhyeok Lee**, Chaewon Park, Sungjun Jang, Minjung Kim, Sangyoun Lee
      * **Superpixel Group-Correlation Network for Co-Saliency Detection (ICIP 2022)**
        - **Minhyeok Lee**, Chaewon Park, Suhwan Cho, Sangyoun Lee
      * **Saliency Detection via Global Context Enhanced Feature Fusion and Edge Weighted Loss (ICIP 2022)** <a href="https://arxiv.org/pdf/2110.06550.pdf">[Paper]</a>
        - Chaewon Park\*, __Minhyeok Lee\*__, MyeongAh Cho, Sangyoun Lee
      * **Robust Lane Detection via Expanded Self Attention (WACV 2022)** <a href="https://openaccess.thecvf.com/content/WACV2022/papers/Lee_Robust_Lane_Detection_via_Expanded_Self_Attention_WACV_2022_paper.pdf">[Paper]</a> <a href="https://github.com/Hydragon516/ESA-official">[Code]</a>
        - **Minhyeok Lee**, Junhyeop Lee, Dogyoon Lee, Woojin Kim, Sangwon Hwang, Sangyoun Lee
      * **EdgeConv with Attention Module for Monocular Depth Estimation (WACV 2022)** <a href="https://openaccess.thecvf.com/content/WACV2022/papers/Lee_EdgeConv_With_Attention_Module_for_Monocular_Depth_Estimation_WACV_2022_paper.pdf">[Paper]</a>
        - **Minhyeok Lee**, Sangwon Hwang, Chaewon Park, Sangyoun Lee
      * **FastAno: Fast Anomaly Detection via Spatio-temporal Patch Transformation (WACV 2022)** <a href="https://openaccess.thecvf.com/content/WACV2022/papers/Park_FastAno_Fast_Anomaly_Detection_via_Spatio-Temporal_Patch_Transformation_WACV_2022_paper.pdf">[Paper]</a>
        - Chaewon Park, MyeongAh Cho, **Minhyeok Lee**, Sangyoun Lee
      * **Multi-level Feature maps Attention for Monocular Depth Estimation (ICCE-Asia 2021)** <a href="https://ieeexplore.ieee.org/document/9641955">[Paper]</a>
        - Seunghoon Lee, **Minhyeok Lee**, Sangyoun Lee
      * **Regularization Strategy for Point Cloud via Rigidly Mixed Sample (CVPR 2021)** <a href="https://openaccess.thecvf.com/content/CVPR2021/papers/Lee_Regularization_Strategy_for_Point_Cloud_via_Rigidly_Mixed_Sample_CVPR_2021_paper.pdf">[Paper]</a> <a href="https://github.com/dogyoonlee/RSMix">[Code]</a>
        - Dogyoon Lee, Jaeha Lee, Junhyeop Lee, Hyeongmin Lee, **Minhyeok Lee**, Sungmin Woo, Sangyoun Lee

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: MVP Lab.
        sub_title: Integrated M.S/Ph.D Student
        caption: July 2020 - present
        link: http://mvp.yonsei.ac.kr
        # quote: >
        #   Image and Video Pattern Recognition Laboratory at Yonsei University
        description: |
          Image and Video Pattern Recognition Laboratory at Yonsei University
      - layout: right
        title: OISL.
        sub_title: Undergraduate Intern
        caption: Jun 2019 - Dec 2019
        link: https://sites.google.com/yonsei.ac.kr/oisl
        # quote: >
        #   Optical Imaging Systems Laboratory
        description: |
          Optical Imaging Systems Laboratory at Yonsei University

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Yonsei University
        sub_title: B.S. in Electrical and Electronic Engineering
        caption: Mar 2017 - Feb 2021
        # quote: >
        #   Short institution or course description (optional)
        description: |
          Got a 2017 Academic Achievement Award.
      - layout: top-right
        title: Hansung Science High School
        sub_title: Physics
        caption: Mar 2014 - Feb 2017
        # quote: >
        #   Short institution or course description (optional)
        # description: |
        #   Got a 2017 Academic Achievement Award.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
